name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Build
      run: go build -ldflags -H=windowsgui -v ./...
      env:
        GOOS: windows
    - name: Install zip
      uses: montudor/action-zip@v1
    - name: Create release zip
      run: zip EldenBackup.zip ./EldenBackup.exe ./Icon.ico
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: EldenBackup
        path: ./EldenBackup.zip
