name: Go

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Install Goversioninfo
      run: go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo
    - name: Go Generate
      run: go generate
    - name: Go Build
      run: go build -ldflags -H=windowsgui -v ./...
      env:
        GOOS: windows
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: EldenBackup
        path: | 
          ./EldenBackup.exe
          ./Icon.ico
